# Global

stages:
  - Platform Tests
  - Analysis

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CTEST_OUTPUT_ON_FAILURE: '1'

# Platform Tests

.platform_unix_template: &platform_unix_template
  stage: Platform Tests
  tags:
    - docker-linux
  script:
    - mkdir build && cd build
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON
    - ninja
    - ctest

.platform_windows_template: &platform_windows_template
  stage: Platform Tests
  tags:
    - docker-windows
  script:
    - echo 'try {'  | out-file -encoding utf8 build.ps1
    - echo 'cd ..; mkdir workdir-cpy' | out-file -encoding utf8 -append build.ps1
    - echo 'Copy-Item C:\workdir\* -Destination C:\workdir-cpy -Recurse' | out-file -encoding utf8 -append build.ps1
    - echo 'cd workdir-cpy' | out-file -encoding utf8 -append build.ps1
    - echo 'mkdir build; cd build' | out-file -encoding utf8 -append build.ps1
    - echo "cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON" | out-file -encoding utf8 -append build.ps1
    - echo 'if(-not $?){throw}' | out-file -encoding utf8 -append build.ps1
    - echo 'ninja' | out-file -encoding utf8 -append build.ps1
    - echo 'if(-not $?){throw}' | out-file -encoding utf8 -append build.ps1
    - echo 'ctest' | out-file -encoding utf8 -append build.ps1
    - echo 'if(-not $?){throw}' | out-file -encoding utf8 -append build.ps1
    - echo '} catch { exit 1 }' | out-file -encoding utf8 -append build.ps1
    - docker run --rm -v ${pwd}:C:\workdir $env:IMAGE C:\workdir\build.ps1

.platform_macos_template: &platform_macos_template
  stage: Platform Tests
  tags:
    - macos
  dependencies: []
  script:
    - mkdir build && cd build
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON
    - ninja
    - ctest

Fedora/GCC:
  image: stabletec/build-foe:fedora-gcc
  <<: *platform_unix_template

Fedora/Clang:
  image: stabletec/build-foe:fedora-clang
  <<: *platform_unix_template

Ubuntu/GCC:
  image: stabletec/build-foe:ubuntu-gcc
  <<: *platform_unix_template

Ubuntu/Clang:
  image: stabletec/build-foe:ubuntu-clang
  <<: *platform_unix_template

Windows/MSVC:
  variables:
    IMAGE: stabletec/build-foe:windows-msvc
  <<: *platform_windows_template

Windows/Clang-cl:
  variables:
    IMAGE: stabletec/build-foe:windows-clang-cl
  <<: *platform_windows_template

.macOS/GCC:
  variables:
    CC: gcc
    CXX: g++
  <<: *platform_macos_template

.macOS/Clang:
  variables:
    CC: clang
    CXX: clang++
  <<: *platform_macos_template

# Analysis
Code Coverage:
  stage: Analysis
  image: stabletec/build-foe:fedora-clang
  tags:
    - docker-linux
  dependencies: []
  script:
    - mkdir build && cd build
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCODE_COVERAGE=ON -DBUILD_TESTS=ON
    - ninja
    - ninja ccov-VkSerializationTests
    - ninja ccov-report-VkSerializationTests
  artifacts:
    name: CodeCoverage
    paths: 
      - build/ccov
    expire_in: 1 day